class_name InputConstants

const ACTIVITY_THRESHOLD: float = 0.2
const MAPPING_THRESHOLD: float = 0.5

const CONTROLLER_TYPES: Dictionary[String, String] = {
	"UNKNOWN": "UNKNOWN",
	"DEFAULT": "DEFAULT",
	"XBOX": "XBOX",
	"PLAYSTATION": "PLAYSTATION",
	"NINTENDO": "NINTENDO",
}

const ACTUATOR_ID_DELIMITER: String = "_"
const ACTUATOR_PREFIXES: Dictionary[String, String] = {
	"UNKNOWN": "UNKNOWN",
	"GAME_PAD_BUTTON": "GAME_PAD_BUTTON",
	"AXIS": "AXIS",
	"MOUSE_BUTTON": "MOUSE_BUTTON",
	"KEY": "KEY",
}
const ACTUATOR_POSTFIXES:  Dictionary[String, String] = {
	"POSITIVE": "POSITIVE",
	"NEGATIVE": "NEGATIVE",
}
const ACTUATOR_NAMES: Dictionary[String, String] = {
	"MOUSE_VELOCITY_X": "MOUSE_VELOCITY_X",
	"MOUSE_VELOCITY_Y": "MOUSE_VELOCITY_Y",
	"ACTUATOR": "ACTUATOR",
}
const MOUSE_VELOCITY_AXES: Dictionary[String, String] = {
	"AXIS_MOUSE_VELOCITY_X_POSITIVE": "AXIS_MOUSE_VELOCITY_X_POSITIVE",
	"AXIS_MOUSE_VELOCITY_X_NEGATIVE": "AXIS_MOUSE_VELOCITY_X_NEGATIVE",
	"AXIS_MOUSE_VELOCITY_Y_POSITIVE": "AXIS_MOUSE_VELOCITY_Y_POSITIVE",
	"AXIS_MOUSE_VELOCITY_Y_NEGATIVE": "AXIS_MOUSE_VELOCITY_Y_NEGATIVE",
}
const GAMEPAD_AXES: Dictionary[String, String] = {
	"AXIS_0_POSITIVE": "AXIS_0_POSITIVE",
	"AXIS_0_NEGATIVE": "AXIS_0_NEGATIVE",
	"AXIS_1_POSITIVE": "AXIS_1_POSITIVE",
	"AXIS_1_NEGATIVE": "AXIS_1_NEGATIVE",
	"AXIS_2_POSITIVE": "AXIS_2_POSITIVE",
	"AXIS_2_NEGATIVE": "AXIS_2_NEGATIVE",
	"AXIS_3_POSITIVE": "AXIS_3_POSITIVE",
	"AXIS_3_NEGATIVE": "AXIS_3_NEGATIVE",
	"AXIS_4_POSITIVE": "AXIS_4_POSITIVE",
	"AXIS_4_NEGATIVE": "AXIS_4_NEGATIVE",
	"AXIS_5_POSITIVE": "AXIS_5_POSITIVE",
	"AXIS_5_NEGATIVE": "AXIS_5_NEGATIVE",
	"AXIS_6_POSITIVE": "AXIS_6_POSITIVE",
	"AXIS_6_NEGATIVE": "AXIS_6_NEGATIVE",
	"AXIS_7_POSITIVE": "AXIS_7_POSITIVE",
	"AXIS_7_NEGATIVE": "AXIS_7_NEGATIVE",
	"AXIS_8_POSITIVE": "AXIS_8_POSITIVE",
	"AXIS_8_NEGATIVE": "AXIS_8_NEGATIVE",
	"AXIS_9_POSITIVE": "AXIS_9_POSITIVE",
	"AXIS_9_NEGATIVE": "AXIS_9_NEGATIVE",
	"AXIS_10_POSITIVE": "AXIS_10_POSITIVE",
	"AXIS_10_NEGATIVE": "AXIS_10_NEGATIVE",
}

const PLAYER_ACTIONS: Dictionary[String, String] = {
	"PLAYER_MOVE_FORWARD": "PLAYER_MOVE_FORWARD",
	"PLAYER_MOVE_BACKWARD": "PLAYER_MOVE_BACKWARD",
	"PLAYER_MOVE_LEFT": "PLAYER_MOVE_LEFT",
	"PLAYER_MOVE_RIGHT": "PLAYER_MOVE_RIGHT",
	"PLAYER_TURN_UP": "PLAYER_TURN_UP",
	"PLAYER_TURN_DOWN": "PLAYER_TURN_DOWN",
	"PLAYER_TURN_LEFT": "PLAYER_TURN_LEFT",
	"PLAYER_TURN_RIGHT": "PLAYER_TURN_RIGHT",
	"PLAYER_RUN": "PLAYER_RUN",
	"PLAYER_JUMP": "PLAYER_JUMP",
	"PLAYER_USE": "PLAYER_USE",
	"PLAYER_DROP": "PLAYER_DROP",
}

const UI_ACTIONS: Dictionary[String, String] = {
	"UI_UP": "UI_UP",
	"UI_DOWN": "UI_DOWN",
	"UI_LEFT": "UI_LEFT",
	"UI_RIGHT": "UI_RIGHT",
	"UI_PAGE_UP": "UI_PAGE_UP",
	"UI_PAGE_DOWN": "UI_PAGE_DOWN",
	"UI_ACCEPT": "UI_ACCEPT",
	"UI_CANCEL": "UI_CANCEL",
	"UI_PAUSE": "UI_PAUSE",
}
